version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_credift
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: DockerFile 
    ports:
      - "80:80" 
    environment:
      - PORT=80 
    restart: always
    

volumes:
  postgres_data: