version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_credift
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: