# Etapa 1 - Imagem base para build
FROM node:20 AS builder

WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./
RUN npm install

# Copia o código-fonte para o container
COPY . .

# Compila o código TypeScript para JavaScript (pasta dist)
RUN npm run build

# Etapa 2 - Imagem base para execução
FROM node:20-alpine

WORKDIR /app

# Copia as dependências de produção (do DokcerFile anterior)
COPY package*.json ./
RUN npm install --omit=dev

# Copia o código já compilado da etapa anterior
COPY --from=builder /app/dist ./dist


EXPOSE 80